### ISSUE TITLE
Adding Glossary On Home Page

### ISSUE THREAD

**Issue by birrielpc** [CBIIT/nci-ctd2-dashboard-tmpl-helper#15]
Please add a Glossary tab (just like the Home tab) on the Home page of the CTD^2 Dashboard Submission Builder page, and provide the text attached. 
[Glossary_for_DB_Submssion_Builder.docx](https://github.com/CBIIT/nci-ctd2-dashboard-tmpl-helper/files/1419271/Glossary_for_DB_Submssion_Builder.docx)

**Comment by birrielpc** [comment]
PDF document has been saved on our OCG file space. Please use the corresponding link:
https://ocg.cancer.gov/sites/default/files/Glossary-for-CTD2-DB-Submission-Builder.pdf

**Comment by kcs3** [comment]
Note - we will use links rather than tabs.

**Comment by kcs3** [comment]
Tested in production release v1.2.1, verified working as specified.
