### ISSUE TITLE
Add Manuscript to Home Page

### ISSUE THREAD

**Issue by birrielpc** [CBIIT/nci-ctd2-dashboard-tmpl-helper#16]
Please add a Manuscript tab (just like the Home tab) on the Home page of the CTD^2 Dashboard Submission Builder page, and link to: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5569694/

**Comment by birrielpc** [comment]
Please use the updated manuscript link: https://www.ncbi.nlm.nih.gov/pubmed/29220450

**Comment by kcs3** [comment]
Note - we will use links rather than tabs.

**Comment by kcs3** [comment]
Tested in production release v1.2.1, verified working as specified.
