### ISSUE TITLE
Adding Manual on Home Page

### ISSUE THREAD

**Issue by birrielpc** [CBIIT/nci-ctd2-dashboard-tmpl-helper#17]
Please add a Manual tab (just like the Home tab) on the Home page of the CTD^2 Dashboard Submission Builder page, and provide the document attached. 
[Updated_Manual_CTD^2_DB_Template_Helper_Tutorial.pdf](https://github.com/CBIIT/nci-ctd2-dashboard-tmpl-helper/files/1428401/Updated_Manual_CTD.2_DB_Template_Helper_Tutorial.pdf)

**Comment by birrielpc** [comment]
Please use this updated document:

**Comment by birrielpc** [comment]
We have further revised the Submission Builder Tutorial manual; please update with this latest copy: 
[CTD^2_DB_SubmissionBuilderTutorial_Updated.pdf](https://github.com/CBIIT/nci-ctd2-dashboard-tmpl-helper/files/1695893/CTD.2_DB_SubmissionBuilderTutorial_Updated.pdf)

**Comment by birrielpc** [comment]
PDF document has been saved within our OCG file space. Please use the corresponding link:
https://ocg.cancer.gov/sites/default/files/CTD2-DB-Submission-Builder-Tutorial.pdf

**Comment by kcs3** [comment]
Note - we will use links rather than tabs.

**Comment by kcs3** [comment]
Tested in production release v1.2.1, verified working as specified.
