### ISSUE TITLE
Update Submission Builder Footer Text 

### ISSUE THREAD

**Issue by birrielpc** [CBIIT/nci-ctd2-dashboard-tmpl-helper#18]
Please update the text within the footer of the Dashboard Template Helper page with the text in the attached document.
[Footer_Text_for Template_Helper.docx](https://github.com/CBIIT/nci-ctd2-dashboard-tmpl-helper/files/1419891/Footer_Text_for.Template_Helper.docx)

**Comment by kcs3** [comment]
The footer text has been updated in Release v1.2.1 as requested.  However, the embedded links should be changed to open in new pages.

**Comment by kcs3** [comment]
Tested in production release v1.2.1, verified working as specified, other than as noted in new issue #30.
