### ISSUE TITLE
Unable to download submission zip file

### ISSUE THREAD

**Issue by vdancik** [CBIIT/nci-ctd2-dashboard-tmpl-helper#34]
The submission zip file for `fhcrc_wee1_phase1_clinical_trial` from  Fred Hutchinson Cancer Research Center (1) is corrupted.

**Comment by kcs3** [comment]
I have inspected the template in the builder.  It has one observation which however is missing some values, specifically for the last of the three compounds, and for the story file.  There is also no observation summary.

When I save the template, the template headers all appear OK, but the observation line is missing.  No error message is displayed.

The template builder is know to be working correctly for other submissions so the question is, what is different about this one?

**Comment by kcs3** [comment]
I added a test observation summary and third compound name.  When I downloaded the template, the observation line was present.

**Comment by kcs3** [comment]
So we won't ever know what the problem was at the time it occured, but it is gone now.  We will just have to keep a watch if any such think occurs again.
