### ISSUE TITLE
Unable to save observation summary

### ISSUE THREAD

**Issue by vdancik** [CBIIT/nci-ctd2-dashboard-tmpl-helper#35]
Error when saving observation summary for `fhcrc_wee1_phase1_clinical_trial` from Fred Hutchinson Cancer Research

summary:

A completed Phase I clinical trial in Stage III/IVB <disease> established that a triplet combination of the <gene_symbol_1> inhibitor <compound_1>, <compound_2>, and <compound_3> is both safe and tolerable, shows promising anti-tumor efficacy and warrants expansion to Phase II clinical trials.

error:

The template data was NOT saved to the server for some unexpected error. Please contact the administrator of this application to help finding out the specific cause and fixing it. Sorry for the inconvenience.

console:

POST [XHR] https://ctd2-dashboard.nci.nih.gov/submit/template/update 
[HTTP/1.1 404 Not Found 189ms]

**Comment by kcs3** [comment]
Is the entire template not saved, or just any observation values entered along with the template?

**Comment by vdancik** [comment]
Looks like only certain entries are not saved as I was able to change a gene name to something else.

**Comment by kcs3** [comment]
It is all working fine now as detailed in #34.
