### ISSUE TITLE
Export - prefix for files

### ISSUE THREAD

**Issue by vdancik** [CBIIT/nci-ctd2-dashboard-tmpl-helper#5]
The proper prefix for files (e.g. images) is "./submissions/<submission_name>/images/ instead of "C:\fakepath<filename>".

**Comment by zhouji2013** [comment]
relevant information https://davidwalsh.name/fakepath

**Comment by zhouji2013** [comment]
* C:\fakepath prefix probably only happens on Linux server, not Windows. I will fix this and verify on a Linux machine.
* Does the proper prefix described here means that the corresponding subdirectory structure must be created for the files? Currently, the attached files and the spreadsheet are stored in the same directory.

**Comment by kcs3** [comment]
Should we just use the more generic "./files/", as there can be more than one type of file uploaded (html, png, SIF)?

**Comment by vdancik** [comment]
To be consistent with existing submissions, I would

- for image files (png,jpeg,tiff, ...) use ./submissions/<submission_name>/images/
- for all other files use ./submissions/<submission_name>/

**Comment by kcs3** [comment]
Note that the template xlsx file itself is at the top of the hierarchy.  The implementation is as specified in Vlado's comment.  Download of zip file tested.

**Comment by zhouji2013** [comment]
In case of further request of fine-tuning the background colors, here is the relevant API information https://poi.apache.org/apidocs/org/apache/poi/hssf/util/HSSFColor.html. f61f6c

**Comment by kcs3** [comment]
Tested in production, working as specified.
