### ISSUE TITLE
Export - missing principal investigator

### ISSUE THREAD

**Issue by vdancik** [CBIIT/nci-ctd2-dashboard-tmpl-helper#7]
Column "principal_investigator" has no values.

**Comment by zhouji2013** [comment]
This is missing from UI.

**Comment by kcs3** [comment]
Can we get it from the knowing the Center that the user selected?

**Comment by kcs3** [comment]
I suggest we add a new text field for entering the PI on the "Submission Description" page, and pre-populate it with the PI for the selected Center.  But allow the user to change it if needed.

**Comment by kcs3** [comment]
Not sure when this was actually put into production, but it is definitely there in 2.1.
